# --- H2 / JPA ---
spring.datasource.url=jdbc:h2:mem:biblioteca;DB_CLOSE_DELAY=-1;MODE=LEGACY
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

# --- MongoDB ---
# Ajusta host/puerto si tu Mongo está en otro sitio.
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=biblioteca

# --- Server ---
server.port=8080

# --- Swagger / OpenAPI ---
springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.path=/v3/api-docs

# Ensure data.sql runs after Hibernate creates tables
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
